# render.yaml

services:
  - name: spring-boot-app
    env:
      - key: SPRING_PROFILES_ACTIVE
        value: production
    buildCommand: ./gradlew build
    startCommand: java -jar build/libs/test-0.0.1-SNAPSHOT.jar
    healthCheckPath: /actuator/health
